/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablemanagementsystem_we_r_05;

import Database.Database;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ravini
 */
public class Tags extends javax.swing.JPanel {
    private String Related_tag;
    PreparedStatement pst;
   Connection conl;
    /**
     * Creates new form Tags
     */
    
    
    public Tags() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TagName = new javax.swing.JTextField();
        TagCode = new javax.swing.JTextField();
        RelatedTag = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AddTagDetails = new javax.swing.JButton();
        ClearFields = new javax.swing.JButton();
        TagJl = new javax.swing.JLabel();
        TagCodeJl = new javax.swing.JLabel();
        RelatedTJl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        updateTagDetails = new javax.swing.JButton();
        DeleteTagDetails = new javax.swing.JButton();
        ClearTagDetials = new javax.swing.JButton();
        tagNameTF = new javax.swing.JTextField();
        tagCodeTf = new javax.swing.JTextField();
        relatedTagTf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        loadTagData = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DisplayTag = new javax.swing.JTable();
        ViewDetails = new javax.swing.JLabel();
        LoadTagDetailsToTable = new javax.swing.JButton();
        SearchTag1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1214, 771));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("                                                          ADD TAGS");
        jLabel1.setToolTipText("");

        TagName.setToolTipText("enter tag name");
        TagName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TagNameMousePressed(evt);
            }
        });
        TagName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TagNameActionPerformed(evt);
            }
        });
        TagName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TagNameKeyPressed(evt);
            }
        });

        TagCode.setToolTipText("Enter tag code");

        RelatedTag.setToolTipText("Enter related tag name");
        RelatedTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatedTagActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Tag name");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Related tag");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Tag code");

        AddTagDetails.setText("Add tag");
        AddTagDetails.setToolTipText("");
        AddTagDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTagDetailsActionPerformed(evt);
            }
        });

        ClearFields.setText("Clear");
        ClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearFieldsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(107, 107, 107)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TagJl)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TagName, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TagCode, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(RelatedTag, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TagCodeJl)
                                    .addComponent(RelatedTJl)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(AddTagDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202)
                        .addComponent(ClearFields, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(378, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TagName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(TagJl)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TagCode, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(TagCodeJl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RelatedTag, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RelatedTJl)
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddTagDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearFields, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add tags", jPanel1);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("                                             MANAGE TAGS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tag id", "Tag name", "Tag code", "Related tag"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        updateTagDetails.setText("Update");
        updateTagDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTagDetailsActionPerformed(evt);
            }
        });

        DeleteTagDetails.setText("Delete");
        DeleteTagDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteTagDetailsActionPerformed(evt);
            }
        });

        ClearTagDetials.setText("Clear");
        ClearTagDetials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearTagDetialsActionPerformed(evt);
            }
        });

        tagNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagNameTFActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Tag name");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Related tag");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Tag code");

        loadTagData.setText("Load data");
        loadTagData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadTagDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tagCodeTf)
                            .addComponent(tagNameTF)
                            .addComponent(relatedTagTf, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))))
                .addContainerGap(347, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(loadTagData, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updateTagDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(DeleteTagDetails, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ClearTagDetials, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(91, 91, 91))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(updateTagDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(DeleteTagDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(ClearTagDetials, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(loadTagData, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tagCodeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(relatedTagTf, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tagNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(58, 58, 58))
        );

        jTabbedPane2.addTab("Manage tags", jPanel2);

        DisplayTag.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tag id", "Tag name", "Tag code", "Related tag"
            }
        ));
        jScrollPane2.setViewportView(DisplayTag);

        ViewDetails.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ViewDetails.setText("                                                        VIEW TAGS");

        LoadTagDetailsToTable.setText("Load tag details");
        LoadTagDetailsToTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadTagDetailsToTableActionPerformed(evt);
            }
        });

        SearchTag1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTag1ActionPerformed(evt);
            }
        });
        SearchTag1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SearchTag1KeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Tag name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(ViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LoadTagDetailsToTable, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(153, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(SearchTag1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(ViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchTag1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(LoadTagDetailsToTable, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jTabbedPane2.addTab("View tags", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Add tags");
    }// </editor-fold>//GEN-END:initComponents

    
    //Insert data to tag table
    private void AddTagDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTagDetailsActionPerformed
        // TODO add your handling code here:
        
        //Input field validation
        String input1 = TagName.getText();
        String input2 = TagCode.getText();
        String input3 = RelatedTag.getText();
        
        
        try{
            
        if(input1.equals("") && input2.equals("") && input3.equals("")){  //Input field validation
            
            TagJl.setText("This field cannot be empty");
            TagCodeJl.setText("This field cannot be empty");
            RelatedTJl.setText("This field cannot be empty");
           
        JOptionPane.showMessageDialog(this, "Input fields cannot be empty","Error",JOptionPane.ERROR_MESSAGE);
        }else if(input1.equals("")){
                  TagJl.setText("This field cannot be empty");
                  JOptionPane.showMessageDialog(this, "Tag name cannot be empty","Error",JOptionPane.ERROR_MESSAGE);
            }else if(input2.equals("")){
                   TagCodeJl.setText("This field cannot be empty");
                   JOptionPane.showMessageDialog(this, "Tag code cannot be empty","Error",JOptionPane.ERROR_MESSAGE);
            } else if(input3.equals("")){
                   RelatedTJl.setText("This field cannot be empty");
                   JOptionPane.showMessageDialog(this, "Related tag cannot be empty","Error",JOptionPane.ERROR_MESSAGE);
            }
        else{
              
  
             Database.setData("Insert into tag values('0','"+TagName.getText()+"','"+TagCode.getText()+"','"+RelatedTag.getText()+"')");
             table_update();
      
        //success msg
        JOptionPane.showMessageDialog(this, " added succesfully","Successful",JOptionPane.INFORMATION_MESSAGE);
       
        }
        }catch(Exception e){
        
        JOptionPane.showMessageDialog(this, "Invalid Input.Re enter details.","Error",JOptionPane.ERROR_MESSAGE);
        System.out.println(e);
        }
    }//GEN-LAST:event_AddTagDetailsActionPerformed

    private void RelatedTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatedTagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelatedTagActionPerformed

//clear fields
    private void ClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearFieldsActionPerformed
        // TODO add your handling code here:
                 TagName.setText("");
                 TagCode.setText("");
                 RelatedTag.setText("");
                 
                 //clear jlabels if they are not empty
                  TagJl.setText("");
            TagCodeJl.setText("");
            RelatedTJl.setText("");
        
    }//GEN-LAST:event_ClearFieldsActionPerformed
//view inserted tag data
    private void LoadTagDetailsToTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadTagDetailsToTableActionPerformed
        // TODO add your handling code here:
        
        
        try{
        
            ResultSet rs= Database.getData("Select * from tag");
            DefaultTableModel tm = (DefaultTableModel)DisplayTag.getModel();
            tm.setRowCount(0);
            
            
             Object[] column = new Object[4];
            while(rs.next()){
                
             
             column[0] = rs.getInt("Tag_id");
             column[1] =  rs.getString("Tag_name");
             column[2] =  rs.getString("Tag_code");
             column[3] =  rs.getString("Related_tag");
           
             tm.addRow(column);
            }
        
    }catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
            System.out.println(e);
            }
        SearchTag1.setText("");
    }//GEN-LAST:event_LoadTagDetailsToTableActionPerformed
//clear fields
    private void ClearTagDetialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearTagDetialsActionPerformed
        // TODO add your handling code here:
        tagNameTF.setText("");
        tagCodeTf.setText("");
        relatedTagTf.setText("");
    }//GEN-LAST:event_ClearTagDetialsActionPerformed
   
    //load data when click on load data btn
    private void loadTagDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadTagDataActionPerformed
        // TODO add your handling code here:
         table_update();
          
    }//GEN-LAST:event_loadTagDataActionPerformed
//Reload table 
    private void table_update(){
        try{
        
            ResultSet rs= Database.getData("Select * from tag");
            DefaultTableModel tm = (DefaultTableModel)jTable1.getModel();
            tm.setRowCount(0);
            
            
             Object[] column = new Object[4];
            while(rs.next()){
                
             
             column[0] = rs.getInt("Tag_id");
             column[1] =  rs.getString("Tag_name");
             column[2] =  rs.getString("Tag_code");
             column[3] =  rs.getString("Related_tag");
           
             tm.addRow(column);
            }
      
    }catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
            System.out.println(e);
            }
         
    }
    
     
    private void updateTagDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTagDetailsActionPerformed
        

       
             DefaultTableModel d1 =(DefaultTableModel)jTable1.getModel();
            int selectIndex =jTable1.getSelectedRow();
            int tagID = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());
            
            
            String TagName = tagNameTF.getText();
            String TagCode = tagCodeTf.getText();
            String RelatedTag = relatedTagTf.getText();
            
            
            
            if(TagName.equals("")  ){
            JOptionPane.showMessageDialog(null,"Tag name is mondotory");
            } else if(TagCode.equals("")){
            JOptionPane.showMessageDialog(null,"Tag code is mondotory");
            }else if(RelatedTag.equals("")){
            JOptionPane.showMessageDialog(null,"Related is mondotory");
            }else{
                
            
            try {
                
            Connection conn =Database.getConnection();
            
            //PreparedStatement editStmt;
            pst = conn.prepareStatement("update tag set  Tag_name = ?,Tag_code=?, Related_tag=? where Tag_id= ?");
 
            pst.setString(1,TagName);
            pst.setString(2,(TagCode));
            pst.setString(3,RelatedTag);
            pst.setInt(4, tagID);
            
            pst.executeUpdate();
            pst.execute();
            JOptionPane.showMessageDialog(this, "Record Updated");
            table_update();
            
            tagNameTF.setText("");
            tagCodeTf.setText("");
            relatedTagTf.setText("");
            tagNameTF.requestFocus();
            
            
            
            } catch (Exception ex) {
         
                JOptionPane.showMessageDialog(this,ex);
                 System.out.println(ex);
            }
            

            }
            
                   
    }//GEN-LAST:event_updateTagDetailsActionPerformed
//load data intothe fields when click on the data in jtable1
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel d1 =(DefaultTableModel)jTable1.getModel();
       int selectIndex =jTable1.getSelectedRow();
       
            tagNameTF.setText(d1.getValueAt(selectIndex, 1).toString());
            tagCodeTf.setText(d1.getValueAt(selectIndex, 2).toString());
            relatedTagTf.setText(d1.getValueAt(selectIndex, 3).toString());
               
    }//GEN-LAST:event_jTable1MouseClicked

    //Delete data in the tag table
    private void DeleteTagDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteTagDetailsActionPerformed
        // TODO add your handling code here:
        
         DefaultTableModel d1 =(DefaultTableModel)jTable1.getModel();
       int selectIndex =jTable1.getSelectedRow();
       int tagID = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());
        
       int dialogResult = JOptionPane.showConfirmDialog(null,"Do you need the delete","warning",JOptionPane.YES_NO_OPTION);
        
        if(dialogResult == JOptionPane.YES_OPTION)
        {
           try {
               
               
            conl =  Database.getConnection();
           
            
            pst = conl.prepareStatement("delete from tag where Tag_id =?");
            pst.setInt(1,tagID);
            pst.executeUpdate();
            table_update();
            tagNameTF.setText("");
            tagCodeTf.setText("");
            relatedTagTf.setText("");
            tagNameTF.requestFocus();
            
            
            
            
          }catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
            System.out.println(e);
            }
        
        }
    }//GEN-LAST:event_DeleteTagDetailsActionPerformed

    private void TagNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TagNameActionPerformed
        // TODO add your handling code here:
    
        
    }//GEN-LAST:event_TagNameActionPerformed
//validate Tagn name text field only to add alphabatical characters
    private void TagNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TagNameKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_TagNameKeyPressed

    private void TagNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TagNameMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TagNameMousePressed

    private void tagNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tagNameTFActionPerformed

    private void SearchTag1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTag1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTag1ActionPerformed
//search keypresses
    private void SearchTag1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchTag1KeyPressed
        // TODO add your handling code here:
           try{
            String code = SearchTag1.getText();
            ResultSet rs= Database.getData("Select * from tag WHERE Tag_name LIKE '%"+code+"%'");
            DefaultTableModel tm = (DefaultTableModel)DisplayTag.getModel();
            tm.setRowCount(0);
           
            
             Object[] column = new Object[4];
            while(rs.next()){
                
          
             column[0] = rs.getInt("Tag_id");
             column[1] =  rs.getString("Tag_name");
             column[2] =  rs.getString("Tag_code");
             column[3] =  rs.getString("Related_tag");
             
             
           
             tm.addRow(column);
            }
      
    }catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
            System.out.println(e);
            }
        
    }//GEN-LAST:event_SearchTag1KeyPressed

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTagDetails;
    private javax.swing.JButton ClearFields;
    private javax.swing.JButton ClearTagDetials;
    private javax.swing.JButton DeleteTagDetails;
    private javax.swing.JTable DisplayTag;
    private javax.swing.JButton LoadTagDetailsToTable;
    private javax.swing.JLabel RelatedTJl;
    private javax.swing.JTextField RelatedTag;
    private javax.swing.JTextField SearchTag1;
    private javax.swing.JTextField TagCode;
    private javax.swing.JLabel TagCodeJl;
    private javax.swing.JLabel TagJl;
    private javax.swing.JTextField TagName;
    private javax.swing.JLabel ViewDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton loadTagData;
    private javax.swing.JTextField relatedTagTf;
    private javax.swing.JTextField tagCodeTf;
    private javax.swing.JTextField tagNameTF;
    private javax.swing.JButton updateTagDetails;
    // End of variables declaration//GEN-END:variables
}
