/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablemanagementsystem_we_r_05;

import Database.Database;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DELL
 */
public class Working_days_and_hours extends javax.swing.JPanel {

    String day = "";
    String day2 = "";
    String hTime, mTime, Time;
    String type;

    /**
     * Creates new form Working_days_and_hours
     */
    public Working_days_and_hours() {
        initComponents();
        showWorkingDaysAndHours();
        viewTimeSlot();
        clearFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        Thursday = new javax.swing.JCheckBox();
        Wednesday = new javax.swing.JCheckBox();
        Tuesday = new javax.swing.JCheckBox();
        Monday = new javax.swing.JCheckBox();
        Friday = new javax.swing.JCheckBox();
        Saturday = new javax.swing.JCheckBox();
        Sunday = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        DeleteButton = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        NextButton = new javax.swing.JButton();
        UpdateTimeSlot = new javax.swing.JButton();
        oneHour = new javax.swing.JRadioButton();
        thirtyMin = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        timeSlotDelete = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        timeSlotClear = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        jInternalFrame1.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Add Working Days and Hours");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("No of working days :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Working days :");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        jComboBox2.setToolTipText("");
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox1.setText("Monday");
        jCheckBox1.setPreferredSize(new java.awt.Dimension(93, 25));

        jCheckBox2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox2.setText("Friday");
        jCheckBox2.setMaximumSize(new java.awt.Dimension(73, 25));
        jCheckBox2.setMinimumSize(new java.awt.Dimension(73, 25));

        jCheckBox3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox3.setText("Tuesday");
        jCheckBox3.setMaximumSize(new java.awt.Dimension(73, 25));
        jCheckBox3.setMinimumSize(new java.awt.Dimension(73, 25));
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox4.setText("Saturday");
        jCheckBox4.setMaximumSize(new java.awt.Dimension(73, 25));
        jCheckBox4.setMinimumSize(new java.awt.Dimension(73, 25));

        jCheckBox5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox5.setText("Wednesday");
        jCheckBox5.setMaximumSize(new java.awt.Dimension(73, 25));
        jCheckBox5.setMinimumSize(new java.awt.Dimension(73, 25));
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox6.setText("Sunday");
        jCheckBox6.setMaximumSize(new java.awt.Dimension(73, 25));
        jCheckBox6.setMinimumSize(new java.awt.Dimension(73, 25));
        jCheckBox6.setPreferredSize(new java.awt.Dimension(73, 25));
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jCheckBox7.setText("Thursday");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Working time per day :");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 15));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("hrs");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("min");

        save.setBackground(new java.awt.Color(153, 153, 153));
        save.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(87, 87, 87)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCheckBox7)
                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel6)))
                                    .addGap(18, 18, 18)
                                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jCheckBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel7))))
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(save, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))))
                .addContainerGap(357, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(427, 427, 427))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(73, 73, 73)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox7)
                .addGap(53, 53, 53)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(63, 63, 63)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Working Days and Hours ", jInternalFrame1);

        jInternalFrame2.setVisible(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "No of working days", "Working days", "Working time per day"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(50);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(2).setMinWidth(500);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(500);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(500);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Working time per day :");

        Thursday.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Thursday.setText("Thursday");

        Wednesday.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Wednesday.setText("Wednesday");
        Wednesday.setMaximumSize(new java.awt.Dimension(73, 25));
        Wednesday.setMinimumSize(new java.awt.Dimension(73, 25));
        Wednesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WednesdayActionPerformed(evt);
            }
        });

        Tuesday.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Tuesday.setText("Tuesday");
        Tuesday.setMaximumSize(new java.awt.Dimension(73, 25));
        Tuesday.setMinimumSize(new java.awt.Dimension(73, 25));
        Tuesday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuesdayActionPerformed(evt);
            }
        });

        Monday.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Monday.setText("Monday");
        Monday.setPreferredSize(new java.awt.Dimension(93, 25));

        Friday.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Friday.setText("Friday");
        Friday.setMaximumSize(new java.awt.Dimension(73, 25));
        Friday.setMinimumSize(new java.awt.Dimension(73, 25));

        Saturday.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Saturday.setText("Saturday");
        Saturday.setMaximumSize(new java.awt.Dimension(73, 25));
        Saturday.setMinimumSize(new java.awt.Dimension(73, 25));

        Sunday.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Sunday.setText("Sunday");
        Sunday.setMaximumSize(new java.awt.Dimension(73, 25));
        Sunday.setMinimumSize(new java.awt.Dimension(73, 25));
        Sunday.setPreferredSize(new java.awt.Dimension(73, 25));
        Sunday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SundayActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Working days :");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("No of working days :");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        jComboBox4.setToolTipText("");
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("ID");

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jToggleButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jToggleButton1.setText("CLEAR");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jToggleButton2.setText("UPDATE");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        DeleteButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        DeleteButton.setText("DELETE");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("Manage Working Days and Hours");

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Search");

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(384, 384, 384))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(97, 97, 97)
                                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame2Layout.createSequentialGroup()
                                                    .addComponent(Monday, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(Friday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(9, 9, 9))
                                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                                .addComponent(Tuesday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(61, 61, 61)
                                                .addComponent(Saturday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jToggleButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                                .addComponent(jToggleButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Thursday)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                                .addComponent(Wednesday, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(22, 22, 22)
                                                .addComponent(Sunday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(132, 132, 132))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Monday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Friday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tuesday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Saturday, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Wednesday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sunday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Thursday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        jTabbedPane1.addTab("Manage Working Days and Hours", jInternalFrame2);

        jInternalFrame3.setVisible(true);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Time slot        :");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("Add Time Slots ");

        NextButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NextButton.setText("NEXT");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        UpdateTimeSlot.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UpdateTimeSlot.setText("UPDATE");
        UpdateTimeSlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateTimeSlotActionPerformed(evt);
            }
        });

        oneHour.setText(" 1 Hour");
        oneHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneHourActionPerformed(evt);
            }
        });

        thirtyMin.setText(" 30 Minutes");
        thirtyMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirtyMinActionPerformed(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Day", "Time Slot"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Select the day :");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setText("Time slot        :");

        jRadioButton3.setText(" 1 Hour");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText(" 30 Minutes");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setText("ADD");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        timeSlotDelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        timeSlotDelete.setText("DELETE");
        timeSlotDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeSlotDeleteActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel18.setText("Manage Time Slots ");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Select the day :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 78, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );

        timeSlotClear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        timeSlotClear.setText("CLEAR");
        timeSlotClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeSlotClearActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Search");

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(oneHour)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(thirtyMin))
                            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(timeSlotDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jInternalFrame3Layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(jLabel18))
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(timeSlotClear, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(UpdateTimeSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame3Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton4)))
                        .addComponent(jComboBox5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)))
                                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(oneHour)
                                    .addComponent(thirtyMin))
                                .addGap(309, 309, 309)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4))
                        .addGap(36, 36, 36)
                        .addComponent(UpdateTimeSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(timeSlotDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeSlotClear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Time Slot", jInternalFrame3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void thirtyMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirtyMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thirtyMinActionPerformed

    private void oneHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneHourActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        clearFields();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        if (jComboBox2.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Select no of days !", "no of days not selected !", 2);
        } else {

            if (jCheckBox1.isSelected()) {
                day += jCheckBox1.getText() + " ";
            }
            if (jCheckBox3.isSelected()) {
                day += jCheckBox3.getText() + " ";
            }
            if (jCheckBox5.isSelected()) {
                day += jCheckBox5.getText() + " ";
            }
            if (jCheckBox7.isSelected()) {
                day += jCheckBox7.getText() + " ";
            }
            if (jCheckBox2.isSelected()) {
                day += jCheckBox2.getText() + " ";
            }
            if (jCheckBox4.isSelected()) {
                day += jCheckBox4.getText() + " ";
            }
            if (jCheckBox6.isSelected()) {
                day += jCheckBox6.getText() + " ";
            }

            hTime = jSpinner1.getValue().toString();
            mTime = jSpinner2.getValue().toString();

            Time = hTime + "." + mTime;

            try {
                Database.setData("insert into addworkingdaysandhours values ('0','" + jComboBox2.getSelectedItem() + "','" + day + "','" + Time + "')");
                JOptionPane.showMessageDialog(null, "Data added Suceessfully !");
                 day = "";

                // Database.setData("INSERT INTO locations VALUES('0','" + BuildingNameTF.getText() + "','" + RoomNameTF.getText() + "','" + capacityTF.getText() + "','" + type + "')");
            } catch (Exception ex) {
                Logger.getLogger(Working_days_and_hours.class.getName()).log(Level.SEVERE, null, ex);

            }
//            day = " ";
        }
        jComboBox2.setSelectedItem(null);
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);
        jCheckBox7.setSelected(false);
        jSpinner1.setValue(0);
        jSpinner2.setValue(0);

        showWorkingDaysAndHours();

    }//GEN-LAST:event_saveActionPerformed

    private void WednesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WednesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WednesdayActionPerformed

    private void TuesdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuesdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TuesdayActionPerformed

    private void SundayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SundayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SundayActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel d1 = (DefaultTableModel) jTable1.getModel();
        int selectIndex = jTable1.getSelectedRow();

        jLabel16.setText(d1.getValueAt(selectIndex, 0).toString());
        jComboBox4.setSelectedItem(d1.getValueAt(selectIndex, 1).toString());

        String wdays = d1.getValueAt(selectIndex, 2).toString();
        jTextField1.setText(d1.getValueAt(selectIndex, 3).toString());
        switch (wdays) {
            case "Monday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Wednesday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Thursday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Friday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
            case "Monday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Tuesday ":
                Monday.setSelected(false);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "TuesDay Wednesday ":
                Monday.setSelected(false);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "TuesDay ThursDay ":
                Monday.setSelected(false);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "TuesDay Friday ":
                Monday.setSelected(false);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "TuesDay SaturDay ":
                Monday.setSelected(false);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
            case "TuesDay Sunday ":
                Monday.setSelected(false);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Wednesday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Wednesday Thursday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Wednesday Friday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Wednesday Saturday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
            case "Wednesday Sunday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Thursday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Thursday Friday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Thursday Saturday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
            case "Thursday Sunday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Friday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Friday Saturday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
            case "Friday Sunday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Saturday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
            case "Saturday Sunday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(true);
                break;
            case "Sunday ":
                Monday.setSelected(false);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Monday Tuesday Wednesday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday Thursday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday Friday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Monday Wednesday Thursday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Wednesday Friday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Wednesday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
            case "Monday Wednesday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Monday Thursday Friday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Thursday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
            case "Monday Thursday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Monday Friday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(true);
                Sunday.setSelected(true);
                break;
            case "Monday Friday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Monday Saturday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(false);
                Wednesday.setSelected(false);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(true);
                break;
            case "Monday Tuesday Wednesday Thursday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday Wednesday Friday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday Wednesday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday Wednesday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(false);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Monday Tuesday Wednesday Thursday Friday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday Wednesday Thursday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday Wednesday Thursday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(false);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Monday Tuesday Wednesday Thursday Friday Saturday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(true);
                Saturday.setSelected(true);
                Sunday.setSelected(false);
                break;
            case "Monday Tuesday Wednesday Thursday Friday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(true);
                Saturday.setSelected(false);
                Sunday.setSelected(true);
                break;
            case "Monday Tuesday Wednesday Thursday Friday Saturday Sunday ":
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(true);
                Saturday.setSelected(true);
                Sunday.setSelected(true);
                break;
            default:
                Monday.setSelected(true);
                Tuesday.setSelected(true);
                Wednesday.setSelected(true);
                Thursday.setSelected(true);
                Friday.setSelected(true);
                Saturday.setSelected(true);
                Sunday.setSelected(true);
                break;

        }

//            Faculty1.setSelectedItem(d1.getValueAt(selectIndex, 2).toString());
//            Department1.setSelectedItem(d1.getValueAt(selectIndex, 3).toString());
//            center1.setSelectedItem(d1.getValueAt(selectIndex, 4).toString());
//            level1.setSelectedItem(d1.getValueAt(selectIndex, 5).toString());
//            Bulding1.setSelectedItem(d1.getValueAt(selectIndex, 6).toString());
//            Rank1.setText(d1.getValueAt(selectIndex, 7).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        String dayNo = jComboBox4.getSelectedItem().toString();
        String workingTime = jTextField1.getText().toString();

        if (Monday.isSelected()) {
            day2 += Monday.getText() + " ";
        }
        if (Tuesday.isSelected()) {
            day2 += Tuesday.getText() + " ";
        }
        if (Wednesday.isSelected()) {
            day2 += Wednesday.getText() + " ";
        }
        if (Thursday.isSelected()) {
            day2 += Thursday.getText() + " ";
        }
        if (Friday.isSelected()) {
            day2 += Friday.getText() + " ";
        }
        if (Saturday.isSelected()) {
            day2 += Saturday.getText() + " ";
        }
        if (Sunday.isSelected()) {
            day2 += Sunday.getText() + " ";
        }

        try {
            Database.setData("update addworkingdaysandhours set NoOfWorkingDays ='" + dayNo + "',WorkingTimePerDay='" + workingTime + "',WorkingDays='" + day2 + "' where id= '" + jTable1.getValueAt(jTable1.getSelectedRow(), 0) + "'");
            //Database.setData("update locations set buildingName='" + BuildingName + "', roomName='" + RoomName + "',roomType='" + type + "' ,capacity ='" + Capacity + "'  where id= '" + jTable1.getValueAt(jTable1.getSelectedRow(), 0) + "'");
            JOptionPane.showMessageDialog(null, "Data updated Suceessfully !");
            day2 = "";
            showWorkingDaysAndHours();

            //Database.setData("update locations set buildingName='" + BuildingName + "', roomName='" + RoomName + "',roomType='" + type + "' ,capacity ='" + Capacity + "'  where id= '" + jTable1.getValueAt(jTable1.getSelectedRow(), 0) + "'");
        } catch (Exception ex) {
            Logger.getLogger(Working_days_and_hours.class.getName()).log(Level.SEVERE, null, ex);
        }
        
//        day2 = " ";

    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void UpdateTimeSlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateTimeSlotActionPerformed
        // TODO add your handling code here:
        String day = jComboBox5.getSelectedItem().toString();
        if (jRadioButton3.isSelected()) {
            type = " 1 Hour";
        }
        if (jRadioButton4.isSelected()) {
            type = " 30 Minutes";
        }
        try {
            Database.setData("update timeslot set day = '" + day + "',timeSlot = '" + type + "' where id= '" + jTable2.getValueAt(jTable2.getSelectedRow(), 0) + "'");
            JOptionPane.showMessageDialog(null, "Data updated Suceessfully !");

            // Database.setData("INSERT INTO locations VALUES('0','" + BuildingNameTF.getText() + "','" + RoomNameTF.getText() + "','" + capacityTF.getText() + "','" + type + "')");
        } catch (Exception ex) {
            Logger.getLogger(Working_days_and_hours.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handlin

        viewTimeSlot();

    }//GEN-LAST:event_UpdateTimeSlotActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_NextButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if (oneHour.isSelected()) {
            type = " 1 Hour";
        }
        if (thirtyMin.isSelected()) {
            type = " 30 Minutes";
        }
        try {
            Database.setData("insert into timeslot values ('0','" + jComboBox3.getSelectedItem() + "','" + type + "')");
            JOptionPane.showMessageDialog(null, "Data added Suceessfully !");

            // Database.setData("INSERT INTO locations VALUES('0','" + BuildingNameTF.getText() + "','" + RoomNameTF.getText() + "','" + capacityTF.getText() + "','" + type + "')");
        } catch (Exception ex) {
            Logger.getLogger(Working_days_and_hours.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:

        viewTimeSlot();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();

        try {

            if (row != -1) {

                Database.setData("delete from addworkingdaysandhours where id ='" + dtm.getValueAt(row, 0) + "'");
                JOptionPane.showMessageDialog(null, "Item Deleted Sucessfully !");
                dtm.removeRow(row);
                showWorkingDaysAndHours();
                clearFields();

            } else {

                JOptionPane.showMessageDialog(null, "Select Delete Item From Item Table !", " Item Not Selected !", 2);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel d1 = (DefaultTableModel) jTable2.getModel();
        int selectIndex = jTable2.getSelectedRow();

        jComboBox5.setSelectedItem(d1.getValueAt(selectIndex, 1).toString());
        String timeSlot = (d1.getValueAt(selectIndex, 2).toString());
        if (timeSlot.equals(" 1 Hour")) {
            jRadioButton3.setSelected(true);
        } else if (timeSlot.equals(" 30 Minutes")) {
            jRadioButton4.setSelected(true);
        } else {
            jRadioButton3.setSelected(false);
            jRadioButton4.setSelected(false);
        }

//        String wdays = d1.getValueAt(selectIndex, 2).toString();
//        jTextField1.setText(d1.getValueAt(selectIndex, 3).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void timeSlotDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeSlotDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
        int row = jTable2.getSelectedRow();

        try {

            if (row != -1) {

                Database.setData("delete from timeslot where id ='" + dtm.getValueAt(row, 0) + "'");
                JOptionPane.showMessageDialog(null, "Item Deleted Sucessfully !");
                dtm.removeRow(row);
                showWorkingDaysAndHours();
                clearFields();

            } else {

                JOptionPane.showMessageDialog(null, "Select Delete Item From Item Table !", " Item Not Selected !", 2);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_timeSlotDeleteActionPerformed

    private void timeSlotClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeSlotClearActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_timeSlotClearActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
        String search = jTextField2.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel) jTable2.getModel();
        String search = jTextField3.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        jTable2.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_jTextField3KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton DeleteButton;
    private javax.swing.JCheckBox Friday;
    private javax.swing.JCheckBox Monday;
    private javax.swing.JButton NextButton;
    private javax.swing.JCheckBox Saturday;
    private javax.swing.JCheckBox Sunday;
    private javax.swing.JCheckBox Thursday;
    private javax.swing.JCheckBox Tuesday;
    private javax.swing.JButton UpdateTimeSlot;
    private javax.swing.JCheckBox Wednesday;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JRadioButton oneHour;
    private javax.swing.JButton save;
    private javax.swing.JRadioButton thirtyMin;
    private javax.swing.JButton timeSlotClear;
    private javax.swing.JButton timeSlotDelete;
    // End of variables declaration//GEN-END:variables

    private void showWorkingDaysAndHours() {
        try {

            TableColumnModel tcm = jTable1.getColumnModel();

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            ResultSet rs = Database.getData("SELECT * FROM addworkingdaysandhours");
            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("id"));
                v.add(rs.getString("NoOfWorkingDays"));
                v.add(rs.getString("WorkingDays"));
                v.add(rs.getString("WorkingTimePerDay"));

                dtm.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void clearFields() {

        jComboBox4.setSelectedItem(null);
        jComboBox2.setSelectedItem(null);
        Monday.setSelected(false);
        Tuesday.setSelected(false);
        Wednesday.setSelected(false);
        Thursday.setSelected(false);
        Friday.setSelected(false);
        Saturday.setSelected(false);
        Sunday.setSelected(false);
        jTextField1.setText(null);
        oneHour.setSelected(false);
        thirtyMin.setSelected(false);
        jComboBox3.setSelectedItem(null);
        jComboBox5.setSelectedItem(null);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
        jLabel16.setText(null);
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);
        jCheckBox7.setSelected(false);
        jSpinner1.setValue(0);
        jSpinner2.setValue(0);

    }

    public void viewTimeSlot() {

        try {

            TableColumnModel tcm = jTable2.getColumnModel();

            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            dtm.setRowCount(0);
            ResultSet rs = Database.getData("SELECT * FROM timeslot");
            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("id"));
                v.add(rs.getString("day"));
                v.add(rs.getString("timeSlot"));

                dtm.addRow(v);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
